//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_LV_Kristina_Garcia_Francisco.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzaPanDBEntities : DbContext
    {
        public PizzaPanDBEntities()
            : base("name=PizzaPanDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblIngredient> tblIngredients { get; set; }
        public virtual DbSet<tblPizza> tblPizzas { get; set; }
        public virtual DbSet<tblPizzaIngredient> tblPizzaIngredients { get; set; }
    }
}
