//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_LV_Kristina_Garcia_Francisco.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPizzaIngredient
    {
        public int PizzaIngredientID { get; set; }
        public int PizzaID { get; set; }
        public int IngredientID { get; set; }
    
        public virtual tblIngredient tblIngredient { get; set; }
        public virtual tblPizza tblPizza { get; set; }
    }
}
